config/routes.rb
CarCompass::Application.routes.draw do

  get "car_articles/new"

  devise_for :admins

  devise_for :dealers

  resources :dealers do
    resources :vehicles, :path => 'vehicle'
  end

  resources 'car-articles', :as => :articles, :controller => :articles

  #scope :contraints => { :protocol => 'https' } do
  resources :charges
  #end


  resources :buyers

  resources 'sold-vehicles', :as => :sold_vehicles, :controller => :sold_vehicles

  match 'vehicles/search' => 'vehicles#search'

  resources :vehicles

  match 'dealer/:id/all-vehicles' => 'dealer_vehicles#index', :as => :dealer_inventory

  match 'dealers/:dealer_id/vehicles/:id' => 'vehicles#old_show_vehicle'

  #Admin--------------------------------------------------------------------
  match 'all-articles' => 'articles#all_articles', :as => :all_articles
  ######-----------------------------------------------------------------------

  match 'find-car/success' => 'buyers#success'

  #contact_dealers-------------------------------------------------------------
  #match 'email-dealer'  => 'email_dealers#email_dealer_about_car', :as => 'email_dealer', :via => :get
  match 'email-dealer' => 'email_dealers#new', :as => 'email_dealer', :via => :get
  match 'email-dealer'  => 'email_dealers#create', :as => 'email_dealer', :via => :post
  ######-----------------------------------------------------------------------

  #contact_form----------------------------------------------------------------
  match 'contact'          => 'contact#new', :as => 'contact', :via => :get
  match 'contact'          => 'contact#create', :as => 'contact', :via => :post
  ######-----------------------------------------------------------------------

  #response_router-------------------------------------------------------------
  match 'router/response-sms'                       => 'routers#response_sms'
  ######-----------------------------------------------------------------------

  match 'incoming-payments'  => 'incoming_payments#create', :via => :post

  #general_pages---------------------------------------------------------------
  match 'thank-you'                     => 'pages#thank_you', :as => :thank_you
  match 'privacy'                       => 'pages#privacy'
  match 'how-it-works'                  => 'pages#how_it_works'
  match 'about'                         => 'pages#about'
  match 'car-articles'                  => 'pages#car_articles'
  root :to                              => 'buyers#new'
  ######-----------------------------------------------------------------------
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :description, :keywords, :permalink, :title, :topic

  validates_presence_of :content, :description, :keywords, :permalink, :title, :topic 

  validates_uniqueness_of :permalink

  def to_param
    permalink
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]

  def new
    @title = "Create A New Car Article"
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "Success! Article created"
      redirect_to "/car-articles/#{@article.permalink}/"
    else
      flash[:notice] = "The article was not saved"
      redirect_to :back
    end
  end

  def show
    @article     = Article.find_by_permalink!(params[:id])
    @title       = @article.title
    @description = @article.description
    @keywords    = @article.keywords
  end

  def edit
    @article = Article.find_by_permalink!(params[:id])
  end

  def update
    @article = Article.find_by_permalink!(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = "The article was successfully updated"
      redirect_to "/car-articles/#{@article.permalink}/"
    else
      flash[:notice] = "Article Didn't Save!"
      redirect_to :back
    end
  end

  def index
    @title       = "Tips Buying A Car Or Truck In Utah"
    @description = "A collection of articles to help Utah car buyers find a great car."
    @keywords    = "Utah, Cars, Trucks, Buying, Research, Financing, Car Loans"
  end

  def destroy
    @article = Article.find_by_permalink!(params[:id])
    if @article.destroy
      flash[:notice] = "The article was deleted"
      redirect_to "/how-many-articles"
    else
      flash[:notice] = "The article was deleted"
      redirect_to :back
    end
  end

  def all_articles
    @articles = Article.all
  end

end

app/views/articles/_edit_article_form.html.erb
<div class="index-buffer"></div>
<%= form_for @article do |f| %>
  <%= f.label :permalink %>
  <%= f.text_field :permalink, :cols => "60" %><br />
  <%= f.label :topic %>
  <%= f.text_field :topic, :size => "30x10" %><br />
  <%= f.label :title %>
  <%= f.text_field :title %><br />
  <%= f.label :description %>
  <%= f.text_field :description %><br />
  <%= f.label :keywords %>
  <%= f.text_field :keywords %><br />
  <%= f.label :content %>
  <%= f.text_area :content, :class => 'add-article'%><br />
  <br />
  <%= f.submit "Update", :class => "btn btn-primary" %>
<% end %>
<%= link_to "Delete article", article_path, :data => { :confirm => "Are you sure?" }, :method => :delete, :class => "btn btn-danger" %>

app/views/articles/_new_article_form.html.erb
<div class="index-buffer"></div>
<%= form_for @article do |f| %>
  <%= f.label :permalink %>
  <%= f.text_field :permalink, :cols => "60" %><br />
  <%= f.label :topic %>
  <%= f.text_field :topic, :size => "30x10" %><br />
  <%= f.label :title %>
  <%= f.text_field :title %><br />
  <%= f.label :description %>
  <%= f.text_field :description %><br />
  <%= f.label :keywords %>
  <%= f.text_field :keywords %><br />
  <%= f.label :content %>
  <%= f.text_area :content, :class => 'add-article'%><br />
  <br />
  <%= f.submit "Add Article", :class => "btn btn-primary" %>
<% end %>

app/views/articles/all_articles.html.erb
<p>You have published <b><%= @articles.size %> articles</b> to Car Compass</p>
<p><b>Topics:</b></p>
<p>
<% @articles.each do |a| %>
  <a href="/car-articles/<%= a.permalink %>" ><%= a.topic %></a> <br /> 
<% end %>
</p>

app/views/articles/edit.html.erb
<h1>Edit</h1>
<%= render 'edit_article_form' %>

app/views/articles/index.html.erb
<div class="page-header">
  <h1>Utah Car and Truck Tips <small>for finding and maintaining your car</small></h1>
</div>
<div id="articles-wrap">
  <div class="span3">
    <h2>Buying</h2>
    <p>Browse our collection of articles
    aimed to help you buy a car or truck in Utah.</p>
    <p><a class="btn" href="/car-articles/buying/">Buying Cars &raquo;</a></p>
  </div>
  <div class="span3">
    <h2>Financing</h2>
    <p>Tips to find financing for utah used cars.</p>
    <p><a class="btn" href="/car-articles/financing/">More Financing &raquo;</a></p>
  </div>
  <div class="span3">
    <h2>Maintenance</h2>
    <p>Common car maintenance articles
    to help you get the most out of your car.</p>
    <p><a class="btn" href="/car-articles/maintenance/">Maintenance Tips &raquo;</a></p>
  </div>
  <div class="span3">
    <h2>Great Cars for Utah</h2>
    <p>Explore some of the more popular
    make and model of cars found in Utah.</p>
    <p><a class="btn" href="/car-articles/great-utah-cars/">Great Utah Cars &raquo;</a></p>
  </div>
</div>

<div class="index-buffer"></div>

app/views/articles/new.html.erb
<h1>Add an Article</h1>
<%= render 'new_article_form' %>

app/views/articles/show.html.erb
<h1><%= markdown(@article.topic) %></h1>
<hr>
<p><%= markdown(@article.content) %></p>
<%if admin_signed_in? %>
  <div class="btn">
    <%= link_to "Edit Article", edit_article_path(@article) %>
  </div>
<% end %> 