config/routes.rb
CarCompass::Application.routes.draw do

  get "car_articles/new"

  devise_for :admins

  devise_for :dealers

  resources :dealers do
    resources :vehicles, :path => 'vehicle'
  end

  resources 'car-articles', :as => :articles, :controller => :articles

  #scope :contraints => { :protocol => 'https' } do
  resources :charges
  #end


  resources :buyers

  resources 'sold-vehicles', :as => :sold_vehicles, :controller => :sold_vehicles

  match 'vehicles/search' => 'vehicles#search'

  resources :vehicles

  match 'dealer/:id/all-vehicles' => 'dealer_vehicles#index', :as => :dealer_inventory

  match 'dealers/:dealer_id/vehicles/:id' => 'vehicles#old_show_vehicle'

  #Admin--------------------------------------------------------------------
  match 'all-articles' => 'articles#all_articles', :as => :all_articles
  ######-----------------------------------------------------------------------

  match 'find-car/success' => 'buyers#success'

  #contact_dealers-------------------------------------------------------------
  #match 'email-dealer'  => 'email_dealers#email_dealer_about_car', :as => 'email_dealer', :via => :get
  match 'email-dealer' => 'email_dealers#new', :as => 'email_dealer', :via => :get
  match 'email-dealer'  => 'email_dealers#create', :as => 'email_dealer', :via => :post
  ######-----------------------------------------------------------------------

  #contact_form----------------------------------------------------------------
  match 'contact'          => 'contact#new', :as => 'contact', :via => :get
  match 'contact'          => 'contact#create', :as => 'contact', :via => :post
  ######-----------------------------------------------------------------------

  #response_router-------------------------------------------------------------
  match 'router/response-sms'                       => 'routers#response_sms'
  ######-----------------------------------------------------------------------

  match 'incoming-payments'  => 'incoming_payments#create', :via => :post

  #general_pages---------------------------------------------------------------
  match 'thank-you'                     => 'pages#thank_you', :as => :thank_you
  match 'privacy'                       => 'pages#privacy'
  match 'how-it-works'                  => 'pages#how_it_works'
  match 'about'                         => 'pages#about'
  match 'car-articles'                  => 'pages#car_articles'
  root :to                              => 'buyers#new'
  ######-----------------------------------------------------------------------
end

app/views/shared/_alerts.html.erb
<% if !notice.nil? %>
  <p class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
  </p>
<% end %>
<% if !alert.nil? %>
  <p class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= alert %>
  </p>
<% end %>

app/views/shared/_authentication.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Car Compass</a>
      <form class="navbar-form pull-right">
        <%= link_to "Random Car", dealer_vehicle_path(random_vehicle.dealer_id, random_vehicle), :class => "btn" %>
        ""<%= link_to "Browse All Cars", vehicles_path, :class => "btn" %>
        <%if dealer_signed_in? %>
          ""<%= link_to "Your Inventory", dealer_inventory_path(session['warden.user.dealer.key'][1].first), :class => "btn btn-primary" %>
          ""<%= link_to "Settings", edit_dealer_registration_path, :class => "btn btn-primary" %>
          ""<%= link_to "Sign out", destroy_dealer_session_path, :method => :delete, :class => "btn btn-primary" %>
        <% end %>
        <% if admin_signed_in? %>
          ""<%= link_to "Add Articles", new_article_path,  :class => "btn btn-primary" %>
          ""<%= link_to "All Articles", all_articles_path, :class => "btn btn-primary" %>
          ""<%= link_to "Admin Sign Out", destroy_admin_session_path, :method => :delete, :class => "btn btn-primary" %>
       <% end %>
      </form>
    </div>
  </div>
  <% if dealer_signed_in? %>
    <% if dealer_billing_not_current?(session['warden.user.dealer.key'][1].first) %>
      <div class="container">
        <div class="activate-account">
          <%= link_to "Add Billing Info to Activate Your Account", 'https://car-compass.herokuapp.com/charges/new/', :class => "btn btn-large btn-block btn-danger" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">×</button> 
    <p>Looks like there is a mistake:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>    

app/views/shared/_footer.html.erb
<hr>
<footer>
<div id="footer-right"><p><a href="/how-it-works/">How It Works</a> |
  <a href="/car-articles/">Car Tips</a> | <a href="/contact/">Contact</a></p></div>
<p>&copy; Car Compass 2013</p>
<br />
<small>Car Compass is a realtime automobile search. We serve all of Utah,
from Ogden and Salt Lake to Provo and Orem. Our goal is to make finding your next car a fun and simple experience.</small>
</footer>
<br />
<br />