config/routes.rb
CarCompass::Application.routes.draw do

  get "car_articles/new"

  devise_for :admins

  devise_for :dealers

  resources :dealers do
    resources :vehicles, :path => 'vehicle'
  end

  resources 'car-articles', :as => :articles, :controller => :articles

  #scope :contraints => { :protocol => 'https' } do
  resources :charges
  #end


  resources :buyers

  resources 'sold-vehicles', :as => :sold_vehicles, :controller => :sold_vehicles

  match 'vehicles/search' => 'vehicles#search'

  resources :vehicles

  match 'dealer/:id/all-vehicles' => 'dealer_vehicles#index', :as => :dealer_inventory

  match 'dealers/:dealer_id/vehicles/:id' => 'vehicles#old_show_vehicle'

  #Admin--------------------------------------------------------------------
  match 'all-articles' => 'articles#all_articles', :as => :all_articles
  ######-----------------------------------------------------------------------

  match 'find-car/success' => 'buyers#success'

  #contact_dealers-------------------------------------------------------------
  #match 'email-dealer'  => 'email_dealers#email_dealer_about_car', :as => 'email_dealer', :via => :get
  match 'email-dealer' => 'email_dealers#new', :as => 'email_dealer', :via => :get
  match 'email-dealer'  => 'email_dealers#create', :as => 'email_dealer', :via => :post
  ######-----------------------------------------------------------------------

  #contact_form----------------------------------------------------------------
  match 'contact'          => 'contact#new', :as => 'contact', :via => :get
  match 'contact'          => 'contact#create', :as => 'contact', :via => :post
  ######-----------------------------------------------------------------------

  #response_router-------------------------------------------------------------
  match 'router/response-sms'                       => 'routers#response_sms'
  ######-----------------------------------------------------------------------

  match 'incoming-payments'  => 'incoming_payments#create', :via => :post

  #general_pages---------------------------------------------------------------
  match 'thank-you'                     => 'pages#thank_you', :as => :thank_you
  match 'privacy'                       => 'pages#privacy'
  match 'how-it-works'                  => 'pages#how_it_works'
  match 'about'                         => 'pages#about'
  match 'car-articles'                  => 'pages#car_articles'
  root :to                              => 'buyers#new'
  ######-----------------------------------------------------------------------
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  attr_accessible :dealer_id, :listed, :make, :model, :price,
                  :year, :description, :mileage, :vin, :city_mpg,
                  :highway_mpg, :transmission, :body, :exterior_color,
                  :interior_color, :drivetrain, :car_type, :cylinders,
                  :images

  validates :dealer_id,   :presence => true
  validates :year,        :presence => true
  validates :make,        :presence => true
  validates :model,       :presence => true
  validates :car_type,    :presence => true
  validates :description, :presence => true
  validates :vin,         :presence => true

  belongs_to :dealer
  has_one :vehicle_statistic

  def to_param
    "#{id} #{make} #{model}".parameterize
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  after_filter :log_view, :only=> [:show]
  after_filter :log_impression, :only=> [:index, :search]

  def index
    @makes    = (Vehicle.where(:listed => true).select(:make).uniq.map { |m| m.make }).sort
    @vehicles = Vehicle.where(:listed => true).paginate(:page => params[:page],
                                                        :per_page => 10).order('id DESC')
    @title    = "Utah Used Cars"
  end

  def show
    @vehicle          = Vehicle.find(params[:id])
    @title            = "#{@vehicle.car_type.titleize} #{@vehicle.make.titleize} #{@vehicle.model.titleize} For Sale In Utah"
    @car_compass_fact = CarCompassFact.all.sample
    @car_tip          = CarTip.where(:kind_of => @vehicle.car_type).last
    @about_make       = AboutMake.where(:make => @vehicle.make).last
  end

  def search
    @vehicles = Search.new(params).find.paginate(:page => params[:page],
                                                 :per_page => 10).order('id DESC')
    @makes    = (@vehicles.map {|v| v.make}).sort
  end

  private

  def log_impression
    UpdateStats.new(current_dealer).log_impressions(@vehicles)
  end

  def log_view
    UpdateStats.new(current_dealer).log_view(@vehicle)
  end

end

app/helpers/vehicles_helper.rb
module VehiclesHelper

  def impressions_for_car(stat)
    if stat.nil?
      "0"
    else
      get_clicks(stat.impressions)
    end
  end

  def clicks_for_car(stat)
    if stat.nil?
      "0"
    else
      get_views(stat.views)
    end
  end

  private

  def get_clicks(stat)
    if stat.nil?
      "0"
    else
      stat
    end
  end

  def get_views(stat)
    if stat.nil?
      "0"
    else
      stat
    end
  end

end

app/views/vehicles/_inventory_nav.html.erb
<p class="lead">Sort By:</p>
<div id="inventory-nav">
  <div class="btn-group">
    <button class="btn btn-small">Make</button>
    <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <% @makes.each do |make| %>
        <li><%= link_to "#{make.capitalize}", vehicles_search_path(:make => make) %></li>
      <% end %>
    </ul>
  </div>
  <div class="btn-group">
    <button class="btn btn-small">Price</button>
    <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to "Below 5,000", vehicles_search_path(:price => "1") %></li>
      <li><%= link_to "5,000 - 10,000", vehicles_search_path(:price => "2") %></li>
      <li><%= link_to "10,000 - 15,000", vehicles_search_path(:price => "3") %></li>
      <li><%= link_to "15,000 - 20,000", vehicles_search_path(:price => "4") %></li>
      <li><%= link_to "Over 20,000", vehicles_search_path(:price => "5") %></li>
    </ul>
  </div>
  <div class="btn-group">
    <button class="btn btn-small">Mileage</button>
    <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to "Low", vehicles_search_path(:miles => "low") %></li>
      <li><%= link_to "Moderate", vehicles_search_path(:miles => "moderate") %></li>
      <li><%= link_to "High", vehicles_search_path(:miles => "high") %></li>
    </ul>
  </div>

</div><!-- inventory-nav --> 
<div class="spacer"></div>
<hr>

app/views/vehicles/_left_show_block.html.erb
<div class="car-title">
  <h1>
    <%= @vehicle.year %>
    <%= @vehicle.make.titleize %>
    <%= @vehicle.model.titleize %>
  </h1>
</div>
<br />
<br />
<div class="big-image">
  <img src=<%= @vehicle.images %> class="img-polaroid" height="300px" width="300px" >
  <h3>
    <% if @vehicle.price ==  0 %>
      Call for price
    <% else %>
      $<%= number_with_delimiter(@vehicle.price, :delimiter => ',') %>
  <% end %>
</h3>
<p class="lead"><%= @vehicle.dealer.phone.to_s.phone_numberize %></p>
<div class="spacer"></div>
<address>
  <strong><%= @vehicle.dealer.dealership %></strong><br>
  <%= @vehicle.dealer.address %><br>
  <%= @vehicle.dealer.city %>,
  <%= @vehicle.dealer.state %>
  <%= @vehicle.dealer.zip %><br>
</address>
<address>
  <%= link_to "Email Seller", email_dealer_path(:vid => @vehicle.id) %>

  <!--<strong>Email seller:</strong><br>
  <a href="mailto:<%= @vehicle.dealer.email %>">
    <%= @vehicle.dealer.email %>
  </a>-->
</address>
</div>

app/views/vehicles/_right_show_block.html.erb
<div class="vehicle-features">
  <h3>Summary</h3>
  <p class="individual-summary">
  <%= @vehicle.description.cap_sentences %>
  </p>
  <%= render :partial => 'show_features', :vehicle => @vehicle %>
  <p class="individual-summary">
  <div class="align-btn">
    <%= link_to "#{@vehicle.dealer.dealership} Inventory", dealer_inventory_path(@vehicle.dealer.id), :class => "btn btn-large btn-block btn-primary" %>
  </div>
  </p>
</div><!-- vehicle features -->
<div class="spacer"></div>

app/views/vehicles/_show_features.html.erb
<h3>Features</h3>
<table class="table table-striped table-condensed">
  <tbody>

    <% if !@vehicle.car_type.nil? %>
      <% if !@vehicle.car_type.empty? %>
        <tr>
          <td><%= @vehicle.car_type.capitalize %></td>
        </tr>
      <% end %>
    <% end %>

    <% if !@vehicle.body.nil? %>
      <% if !@vehicle.body.empty? %>
        <tr>
          <td><%= @vehicle.body.titleize %></td>
        </tr>
      <% end %>
    <% end %>

    <% if !@vehicle.mileage.nil? %>
      <tr>
        <td>Miles: <%= number_with_delimiter(@vehicle.mileage, :delimiter => ',') %></td>
      </tr>
    <% end %>

    <% if !@vehicle.highway_mpg.nil? %>
      <tr>
        <td>MPG Highway: <%= @vehicle.highway_mpg %></td>
      </tr>
    <% end %>

    <% if !@vehicle.city_mpg.nil? %>
      <tr>
        <td>MPG City: <%= @vehicle.city_mpg %></td>
      </tr>
    <% end %>

    <% if !@vehicle.transmission.nil? %>
      <% if !@vehicle.transmission.empty? %>
        <tr>
          <td><%= @vehicle.transmission.capitalize %> Transmission</td>
        </tr>
      <% end %>
    <% end %>

    <% if !@vehicle.drivetrain.nil? %>
      <% if !@vehicle.drivetrain.empty? %>
        <tr>
          <td><%= @vehicle.drivetrain.capitalize %></td>
        </tr>
      <% end %>
    <% end %>

    <% if !@vehicle.exterior_color.nil? %>
      <% if !@vehicle.exterior_color.empty? %>
        <tr>
          <td><%= @vehicle.exterior_color.capitalize %></td>
        </tr>
      <% end %>
    <% end %>

    <% if !@vehicle.interior_color.nil? %>
      <% if !@vehicle.interior_color.empty? %>
        <tr>
          <td><%= @vehicle.interior_color.capitalize %></td>
        </tr>
      <% end %>
    <% end %>

    <% if !@vehicle.cylinders.nil? %>
      <tr>
        <td><%= @vehicle.cylinders %> Cylinders</td>
      </tr>
    <% end %>

    <% if !@vehicle.vin.empty? %>
      <tr>
        <td>VIN: <%= @vehicle.vin %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vehicles/_vehicle.html.erb
<div class="indexed-car">
  <div class="left-box">
    <%= link_to(image_tag("#{vehicle.images}", :size => "140x140", :alt => "#{vehicle.make} #{vehicle.model}", :class => 'img-polaroid'), dealer_vehicle_path(vehicle.dealer_id, vehicle))%>
    <p><strong>
      <% if vehicle.price == 0 %>
        Call for price
      <% else %>
        $<%= number_with_delimiter(vehicle.price, :delimiter => ',') %>
    <% end %>
  <br />
  <% if dealer_signed_in? %>
    <% if current_dealer.id == vehicle.dealer_id %>
      <small> Impr: <%= impressions_for_car(vehicle.vehicle_statistic) %> Clicks: <%= clicks_for_car(vehicle.vehicle_statistic) %></small>
    <% end %>
  <% end %>
  </strong></p>
</div><!-- left-box -->
<div class="vehicle-summary">
  <h3>
    <%= link_to "#{vehicle.year} #{vehicle.make.titleize} #{vehicle.model.titleize}", dealer_vehicle_path(vehicle.dealer_id, vehicle) %>
  </h3>
  <p><%= vehicle.description.cap_sentences %>
<br />
<br />
<%= link_to '<button class="btn btn-mini btn-primary" type="button" >Learn More</button>'.html_safe, dealer_vehicle_path(vehicle.dealer_id, vehicle) %>
</p>
  </div><!-- vehicle-summary -->
</div><!-- indexed-car -->
<div class="index-buffer"></div>
<div class="spacer"></div>
<hr>

app/views/vehicles/index.html.erb
<div id="vehicle-index-wrapper">
  <%= render 'inventory_nav' %>
  <%= render @vehicles %>
  <%= will_paginate @vehicles, :renderer => 'BootstrapPaginationHelper::LinkRenderer' %>
</div>

app/views/vehicles/search.html.erb
<!-- Search -->
<div id="vehicle-index-wrapper">
  <%= render 'inventory_nav' %>
  <%= render @vehicles %>
  <%= will_paginate @vehicles, :renderer => 'BootstrapPaginationHelper::LinkRenderer' %>
</div>

app/views/vehicles/show.html.erb
<!--  LEFT BLOCK -->
<%= render :partial => 'left_show_block', :vehicle => @vehicle %>
<!--  RIGHT BLOCK -->
<%= render :partial => 'right_show_block', :vehicle => @vehicle %>
<br />
<br />
<hr >
<div class="left-block">
  <h4>Car Compass FAQ</h4>
  <p>
  <%= @car_compass_fact.fact %>
  </p>
</div>
<% if !@about_make.nil? %>
  <div class="right-block">
    <h4>About <%= @vehicle.make.titleize %></h4>
    <p>
    <%= @about_make.summary %>
    </p>
  </div>
<% end %>
<div class="spacer"></div>
<% if !@car_tip.nil? %>
  <div class="big-block">
    <h4><%= @vehicle.car_type.titleize %> Car Tip</h4>
    <p>
    <%= @car_tip.tip %>
    </p>
  </div>
<% end %>
<br />
<br />
<br />
<div class="spacer"></div>